// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Filestore backup.
public struct Backup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the backup, in the format
  /// `projects/{project_number}/locations/{location_id}/backups/{backup_id}`.
  public var name: Swift.String = Swift.String()

  /// A description of the backup with 2048 characters or less.
  /// Requests with longer descriptions will be rejected.
  public var description: Swift.String = Swift.String()

  /// Output only. The backup state.
  public var state: Backup.State = Backup.State()

  /// Output only. The time when the backup was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Resource labels to represent user provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Capacity of the source file share when the backup was created.
  public var capacityGb: Swift.Int64 = Swift.Int64()

  /// Output only. The size of the storage used by the backup. As backups share
  /// storage, this number is expected to change with backup creation/deletion.
  public var storageBytes: Swift.Int64 = Swift.Int64()

  /// The resource name of the source Filestore instance, in the format
  /// `projects/{project_number}/locations/{location_id}/instances/{instance_id}`,
  /// used to create this backup.
  public var sourceInstance: Swift.String = Swift.String()

  /// Name of the file share in the source Filestore instance that the
  /// backup is created from.
  public var sourceFileShare: Swift.String = Swift.String()

  /// Output only. The service tier of the source Filestore instance that this
  /// backup is created from.
  public var sourceInstanceTier: Instance.Tier = Instance.Tier()

  /// Output only. Amount of bytes that will be downloaded if the backup is
  /// restored. This may be different than storage bytes, since sequential
  /// backups of the same disk will share storage.
  public var downloadBytes: Swift.Int64 = Swift.Int64()

  /// Output only. Reserved for future use.
  public var satisfiesPzs: GoogleCloudWkt.BoolValue? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// Immutable. KMS key name used for data encryption.
  public var kmsKey: Swift.String = Swift.String()

  /// Optional. Input only. Immutable. Tag key-value pairs bound to this
  /// resource. Each key must be a namespaced name and each value a short name.
  /// Example:
  /// "123456789012/environment" : "production",
  /// "123456789013/costCenter" : "marketing"
  /// See the documentation for more information:
  /// - Namespaced name:
  /// https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#retrieving_tag_key
  /// - Short name:
  /// https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#retrieving_tag_value
  public var tags: [Swift.String: Swift.String] = [:]

  /// Output only. The file system protocol of the source Filestore instance that
  /// this backup is created from.
  public var fileSystemProtocol: Instance.FileProtocol = Instance.FileProtocol()

  /// Initialize a new instance of `Backup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Backup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The backup state.
  public enum State: Codable, Equatable, Sendable {
    case unspecified
    case creating
    case finalizing
    case ready
    case deleting
    case invalid
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .finalizing: return 2
      case .ready: return 3
      case .deleting: return 4
      case .invalid: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .finalizing: return "FINALIZING"
      case .ready: return "READY"
      case .deleting: return "DELETING"
      case .invalid: return "INVALID"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "FINALIZING": self = .finalizing
      case "READY": self = .ready
      case "DELETING": self = .deleting
      case "INVALID": self = .invalid
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .finalizing
      case 3: self = .ready
      case 4: self = .deleting
      case 5: self = .invalid
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .finalizing: return try container.encode(2)
      case .ready: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .invalid: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.filestore.v1.Backup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
