// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Filestore backup.
public struct Backup: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the backup, in the format
  /// `projects/{project_number}/locations/{location_id}/backups/{backup_id}`.
  public var name: Swift.String = Swift.String()

  /// A description of the backup with 2048 characters or less.
  /// Requests with longer descriptions will be rejected.
  public var description: Swift.String = Swift.String()

  /// Output only. The backup state.
  public var state: Backup.State = Backup.State()

  /// Output only. The time when the backup was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Resource labels to represent user provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Capacity of the source file share when the backup was created.
  public var capacityGb: Swift.Int64 = Swift.Int64()

  /// Output only. The size of the storage used by the backup. As backups share
  /// storage, this number is expected to change with backup creation/deletion.
  public var storageBytes: Swift.Int64 = Swift.Int64()

  /// The resource name of the source Filestore instance, in the format
  /// `projects/{project_number}/locations/{location_id}/instances/{instance_id}`,
  /// used to create this backup.
  public var sourceInstance: Swift.String = Swift.String()

  /// Name of the file share in the source Filestore instance that the
  /// backup is created from.
  public var sourceFileShare: Swift.String = Swift.String()

  /// Output only. The service tier of the source Filestore instance that this
  /// backup is created from.
  public var sourceInstanceTier: Instance.Tier = Instance.Tier()

  /// Output only. Amount of bytes that will be downloaded if the backup is
  /// restored. This may be different than storage bytes, since sequential
  /// backups of the same disk will share storage.
  public var downloadBytes: Swift.Int64 = Swift.Int64()

  /// Output only. Reserved for future use.
  public var satisfiesPzs: GoogleCloudWKT.BoolValue? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// Immutable. KMS key name used for data encryption.
  public var kmsKey: Swift.String = Swift.String()

  /// Optional. Input only. Immutable. Tag key-value pairs bound to this
  /// resource. Each key must be a namespaced name and each value a short name.
  /// Example:
  /// "123456789012/environment" : "production",
  /// "123456789013/costCenter" : "marketing"
  /// See the documentation for more information:
  /// - Namespaced name:
  /// https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#retrieving_tag_key
  /// - Short name:
  /// https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#retrieving_tag_value
  public var tags: [Swift.String: Swift.String] = [:]

  /// Output only. The file system protocol of the source Filestore instance that
  /// this backup is created from.
  public var fileSystemProtocol: Instance.FileProtocol = Instance.FileProtocol()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Backup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Backup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let capacityGb = CodingKeys(stringValue: "capacityGb")
    static let storageBytes = CodingKeys(stringValue: "storageBytes")
    static let sourceInstance = CodingKeys(stringValue: "sourceInstance")
    static let sourceFileShare = CodingKeys(stringValue: "sourceFileShare")
    static let sourceInstanceTier = CodingKeys(stringValue: "sourceInstanceTier")
    static let downloadBytes = CodingKeys(stringValue: "downloadBytes")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let satisfiesPzi = CodingKeys(stringValue: "satisfiesPzi")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")
    static let tags = CodingKeys(stringValue: "tags")
    static let fileSystemProtocol = CodingKeys(stringValue: "fileSystemProtocol")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "state",
      "createTime",
      "labels",
      "capacityGb",
      "storageBytes",
      "sourceInstance",
      "sourceFileShare",
      "sourceInstanceTier",
      "downloadBytes",
      "satisfiesPzs",
      "satisfiesPzi",
      "kmsKey",
      "tags",
      "fileSystemProtocol",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Backup.State.self, forKey: .state) {
      self.state = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .capacityGb) {
      self.capacityGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .storageBytes) {
      self.storageBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceInstance) {
      self.sourceInstance = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceFileShare) {
      self.sourceFileShare = value
    }
    if let value = try container.decodeIfPresent(Instance.Tier.self, forKey: .sourceInstanceTier) {
      self.sourceInstanceTier = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .downloadBytes) {
      self.downloadBytes = value
    }
    self.satisfiesPzs = try container.decodeIfPresent(
      GoogleCloudWKT.BoolValue.self, forKey: .satisfiesPzs)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi) {
      self.satisfiesPzi = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
      self.kmsKey = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent(
      Instance.FileProtocol.self, forKey: .fileSystemProtocol)
    {
      self.fileSystemProtocol = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.capacityGb, forKey: .capacityGb)
    try container.encode(self.storageBytes, forKey: .storageBytes)
    try container.encode(self.sourceInstance, forKey: .sourceInstance)
    try container.encode(self.sourceFileShare, forKey: .sourceFileShare)
    try container.encode(self.sourceInstanceTier, forKey: .sourceInstanceTier)
    try container.encode(self.downloadBytes, forKey: .downloadBytes)
    try container.encodeIfPresent(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.satisfiesPzi, forKey: .satisfiesPzi)
    try container.encode(self.kmsKey, forKey: .kmsKey)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.fileSystemProtocol, forKey: .fileSystemProtocol)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The backup state.
  public enum State: Codable, Equatable, Sendable {
    /// State not set.
    case unspecified
    /// Backup is being created.
    case creating
    /// Backup has been taken and the operation is being finalized. At this
    /// point, changes to the file share will not be reflected in the backup.
    case finalizing
    /// Backup is available for use.
    case ready
    /// Backup is being deleted.
    case deleting
    /// Backup is not valid and cannot be used for creating new instances or
    /// restoring existing instances.
    case invalid
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .finalizing: return 2
      case .ready: return 3
      case .deleting: return 4
      case .invalid: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .finalizing: return "FINALIZING"
      case .ready: return "READY"
      case .deleting: return "DELETING"
      case .invalid: return "INVALID"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "FINALIZING": self = .finalizing
      case "READY": self = .ready
      case "DELETING": self = .deleting
      case "INVALID": self = .invalid
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .finalizing
      case 3: self = .ready
      case 4: self = .deleting
      case 5: self = .invalid
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .finalizing: return try container.encode("FINALIZING")
      case .ready: return try container.encode("READY")
      case .deleting: return try container.encode("DELETING")
      case .invalid: return try container.encode("INVALID")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.filestore.v1.Backup"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
