// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudCommon
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class CloudFilestoreManagerLogging: CloudFilestoreManagerStub {
    let inner: any CloudFilestoreManagerStub
    let logger: Logger

    public init(_ inner: any CloudFilestoreManagerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-filestore-v1"
      logger[metadataKey: "gcp.client.service"] = "file"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudFilestoreManager"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInstances",
        action: {
          (r: ListInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudFilestoreV1.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Instance {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInstance",
        action: {
          (r: GetInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudFilestoreV1.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createInstance",
        action: {
          (r: CreateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInstance(request: r, options: o)
        })
    }

    public func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateInstance",
        action: {
          (r: UpdateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateInstance(request: r, options: o)
        })
    }

    public func restoreInstance(
      request: RestoreInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "restoreInstance",
        action: {
          (r: RestoreInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.restoreInstance(request: r, options: o)
        })
    }

    public func revertInstance(
      request: RevertInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "revertInstance",
        action: {
          (r: RevertInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.revertInstance(request: r, options: o)
        })
    }

    public func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteInstance",
        action: {
          (r: DeleteInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteInstance(request: r, options: o)
        })
    }

    public func listSnapshots(
      request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSnapshots",
        action: {
          (r: ListSnapshotsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudFilestoreV1.ListSnapshotsResponse
          in
          return try await self.inner.listSnapshots(request: r, options: o)
        })
    }

    public func getSnapshot(
      request: GetSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Snapshot {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSnapshot",
        action: {
          (r: GetSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudFilestoreV1.Snapshot
          in
          return try await self.inner.getSnapshot(request: r, options: o)
        })
    }

    public func createSnapshot(
      request: CreateSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSnapshot",
        action: {
          (r: CreateSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createSnapshot(request: r, options: o)
        })
    }

    public func deleteSnapshot(
      request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSnapshot",
        action: {
          (r: DeleteSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteSnapshot(request: r, options: o)
        })
    }

    public func updateSnapshot(
      request: UpdateSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSnapshot",
        action: {
          (r: UpdateSnapshotRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateSnapshot(request: r, options: o)
        })
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBackups",
        action: {
          (r: ListBackupsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudFilestoreV1.ListBackupsResponse
          in
          return try await self.inner.listBackups(request: r, options: o)
        })
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Backup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBackup",
        action: {
          (r: GetBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudFilestoreV1.Backup
          in
          return try await self.inner.getBackup(request: r, options: o)
        })
    }

    public func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBackup",
        action: {
          (r: CreateBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackup(request: r, options: o)
        })
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBackup",
        action: {
          (r: DeleteBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackup(request: r, options: o)
        })
    }

    public func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBackup",
        action: {
          (r: UpdateBackupRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackup(request: r, options: o)
        })
    }

    public func promoteReplica(
      request: PromoteReplicaRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "promoteReplica",
        action: {
          (r: PromoteReplicaRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.promoteReplica(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
