// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Configures and manages Filestore resources.
///
/// Filestore Manager v1.
///
/// The `file.googleapis.com` service implements the Filestore API and
/// defines the following resource model for managing instances:
/// * The service works with a collection of cloud projects, named: `/projects/*`
/// * Each project has a collection of available locations, named: `/locations/*`
/// * Each location has a collection of instances and backups, named:
/// `/instances/*` and `/backups/*` respectively.
/// * As such, Filestore instances are resources of the form:
///   `/projects/{project_number}/locations/{location_id}/instances/{instance_id}`
///   and backups are resources of the form:
///   `/projects/{project_number}/locations/{location_id}/backup/{backup_id}`
///
/// Note that location_id must be a Google Cloud `zone` for instances, but
/// a Google Cloud `region` for backups; for example:
/// * `projects/12345/locations/us-central1-c/instances/my-filestore`
/// * `projects/12345/locations/us-central1/backups/my-backup`
///
/// @Snippet(path: "CloudFilestoreManagerQuickstart")
public final class CloudFilestoreManagerClient: Clients.CloudFilestoreManagerProtocol, Sendable {
  let inner: any Clients.CloudFilestoreManagerStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `CloudFilestoreManagerClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudFilestoreManagerStub = try Clients.CloudFilestoreManagerTransport(
      options)
    inner = Clients.CloudFilestoreManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudFilestoreManagerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists all instances in a project for either a specified location
  /// or for all locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Gets the details of a specific instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Creates an instance.
  /// When creating from a backup, the capacity of the new instance needs to be
  /// equal to or larger than the capacity of the backup (and also equal to or
  /// larger than the minimum capacity of the tier).
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateInstance")
  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInstance(request: request, options: options)
  }

  /// Creates an instance.
  /// When creating from a backup, the capacity of the new instance needs to be
  /// equal to or larger than the capacity of the backup (and also equal to or
  /// larger than the minimum capacity of the tier).
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateInstance")
  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.createInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the settings of a specific instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateInstance")
  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateInstance(request: request, options: options)
  }

  /// Updates the settings of a specific instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateInstance")
  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.updateInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Restores an existing instance's file share from a backup.
  ///
  /// The capacity of the instance needs to be equal to or larger than the
  /// capacity of the backup (and also equal to or larger than the minimum
  /// capacity of the tier).
  ///
  /// @Snippet(path: "CloudFilestoreManager_RestoreInstance")
  public func restoreInstance(
    request: RestoreInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.restoreInstance(request: request, options: options)
  }

  /// Restores an existing instance's file share from a backup.
  ///
  /// The capacity of the instance needs to be equal to or larger than the
  /// capacity of the backup (and also equal to or larger than the minimum
  /// capacity of the tier).
  ///
  /// @Snippet(path: "CloudFilestoreManager_RestoreInstance")
  public func restoreInstancePollingUntilDone(
    request: RestoreInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.restoreInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Revert an existing instance's file system to a specified snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_RevertInstance")
  public func revertInstance(
    request: RevertInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.revertInstance(request: request, options: options)
  }

  /// Revert an existing instance's file system to a specified snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_RevertInstance")
  public func revertInstancePollingUntilDone(
    request: RevertInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.revertInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Deletes an instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteInstance")
  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all snapshots in a project for either a specified location
  /// or for all locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListSnapshots")
  public func listSnapshots(
    request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse {
    try await self.inner.listSnapshots(request: request, options: options)
  }

  /// Gets the details of a specific snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetSnapshot")
  public func getSnapshot(
    request: GetSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Snapshot {
    try await self.inner.getSnapshot(request: request, options: options)
  }

  /// Creates a snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateSnapshot")
  public func createSnapshot(
    request: CreateSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createSnapshot(request: request, options: options)
  }

  /// Creates a snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateSnapshot")
  public func createSnapshotPollingUntilDone(
    request: CreateSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Snapshot>.State in
      return try op._extractStatus(Snapshot.self)
    }
    let rawOp = try await self.createSnapshot(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Snapshot>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteSnapshot")
  public func deleteSnapshot(
    request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteSnapshot(request: request, options: options)
  }

  /// Deletes a snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteSnapshot")
  public func deleteSnapshotPollingUntilDone(
    request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteSnapshot(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the settings of a specific snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateSnapshot")
  public func updateSnapshot(
    request: UpdateSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateSnapshot(request: request, options: options)
  }

  /// Updates the settings of a specific snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateSnapshot")
  public func updateSnapshotPollingUntilDone(
    request: UpdateSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Snapshot>.State in
      return try op._extractStatus(Snapshot.self)
    }
    let rawOp = try await self.updateSnapshot(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Snapshot>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all backups in a project for either a specified location or for all
  /// locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListBackups")
  public func listBackups(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse {
    try await self.inner.listBackups(request: request, options: options)
  }

  /// Gets the details of a specific backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetBackup")
  public func getBackup(
    request: GetBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Backup {
    try await self.inner.getBackup(request: request, options: options)
  }

  /// Creates a backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateBackup")
  public func createBackup(
    request: CreateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createBackup(request: request, options: options)
  }

  /// Creates a backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateBackup")
  public func createBackupPollingUntilDone(
    request: CreateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Backup>.State in
      return try op._extractStatus(Backup.self)
    }
    let rawOp = try await self.createBackup(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteBackup")
  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteBackup(request: request, options: options)
  }

  /// Deletes a backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteBackup")
  public func deleteBackupPollingUntilDone(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteBackup(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the settings of a specific backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateBackup")
  public func updateBackup(
    request: UpdateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateBackup(request: request, options: options)
  }

  /// Updates the settings of a specific backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateBackup")
  public func updateBackupPollingUntilDone(
    request: UpdateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Backup>.State in
      return try op._extractStatus(Backup.self)
    }
    let rawOp = try await self.updateBackup(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Promote the standby instance (replica).
  ///
  /// @Snippet(path: "CloudFilestoreManager_PromoteReplica")
  public func promoteReplica(
    request: PromoteReplicaRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.promoteReplica(request: request, options: options)
  }

  /// Promote the standby instance (replica).
  ///
  /// @Snippet(path: "CloudFilestoreManager_PromoteReplica")
  public func promoteReplicaPollingUntilDone(
    request: PromoteReplicaRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Instance>.State in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.promoteReplica(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFilestoreManager_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudFilestoreManagerClient`.
  ///
  /// To mock `CloudFilestoreManagerClient` change your functions to receive
  /// `some CloudFilestoreManagerProtocol` or `any CloudFilestoreManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudFilestoreManagerProtocol: Sendable {
    /// See `CloudFilestoreManagerClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse

    /// See `CloudFilestoreManagerClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Instance

    /// See `CloudFilestoreManagerClient.createInstance`.
    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createInstance`.
    func createInstancePollingUntilDone(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.updateInstance`.
    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateInstance`.
    func updateInstancePollingUntilDone(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.restoreInstance`.
    func restoreInstance(
      request: RestoreInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.restoreInstance`.
    func restoreInstancePollingUntilDone(
      request: RestoreInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.revertInstance`.
    func revertInstance(
      request: RevertInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.revertInstance`.
    func revertInstancePollingUntilDone(
      request: RevertInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteInstance`.
    func deleteInstancePollingUntilDone(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `CloudFilestoreManagerClient.listSnapshots`.
    func listSnapshots(
      request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse

    /// See `CloudFilestoreManagerClient.getSnapshot`.
    func getSnapshot(
      request: GetSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Snapshot

    /// See `CloudFilestoreManagerClient.createSnapshot`.
    func createSnapshot(
      request: CreateSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createSnapshot`.
    func createSnapshotPollingUntilDone(
      request: CreateSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Snapshot>

    /// See `CloudFilestoreManagerClient.deleteSnapshot`.
    func deleteSnapshot(
      request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteSnapshot`.
    func deleteSnapshotPollingUntilDone(
      request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `CloudFilestoreManagerClient.updateSnapshot`.
    func updateSnapshot(
      request: UpdateSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateSnapshot`.
    func updateSnapshotPollingUntilDone(
      request: UpdateSnapshotRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Snapshot>

    /// See `CloudFilestoreManagerClient.listBackups`.
    func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse

    /// See `CloudFilestoreManagerClient.getBackup`.
    func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Backup

    /// See `CloudFilestoreManagerClient.createBackup`.
    func createBackup(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createBackup`.
    func createBackupPollingUntilDone(
      request: CreateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Backup>

    /// See `CloudFilestoreManagerClient.deleteBackup`.
    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteBackup`.
    func deleteBackupPollingUntilDone(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `CloudFilestoreManagerClient.updateBackup`.
    func updateBackup(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateBackup`.
    func updateBackupPollingUntilDone(
      request: UpdateBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Backup>

    /// See `CloudFilestoreManagerClient.promoteReplica`.
    func promoteReplica(
      request: PromoteReplicaRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.promoteReplica`.
    func promoteReplicaPollingUntilDone(
      request: PromoteReplicaRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudFilestoreManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `CloudFilestoreManagerClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `CloudFilestoreManagerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CloudFilestoreManagerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.CloudFilestoreManagerProtocol {
  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudFilestoreV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listInstancesByItems(
    request: ListInstancesRequest
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    self.listInstancesByItems(request: request, options: .init())
  }

  /// Lists all instances in a project for either a specified location
  /// or for all locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListInstances")
  public func listInstancesByItems(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInstancesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return self.listInstancesByItems(request: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudFilestoreV1.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudFilestoreV1.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func createInstance(request: CreateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInstance(request: request, options: .init())
  }

  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createInstancePollingUntilDone(request: CreateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.createInstancePollingUntilDone(request: request, options: .init())
  }

  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInstancePollingUntilDone(
    parent: Swift.String,
    instance: Instance?,
    instanceId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = CreateInstanceRequest().with {
      $0.parent = parent
      $0.instance = instance
      $0.instanceId = instanceId
    }
    return try await self.createInstancePollingUntilDone(request: request)
  }

  public func updateInstance(request: UpdateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateInstance(request: request, options: .init())
  }

  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateInstancePollingUntilDone(request: UpdateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.updateInstancePollingUntilDone(request: request, options: .init())
  }

  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateInstancePollingUntilDone(
    instance: Instance?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = UpdateInstanceRequest().with {
      $0.instance = instance
      $0.updateMask = updateMask
    }
    return try await self.updateInstancePollingUntilDone(request: request)
  }

  public func restoreInstance(request: RestoreInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.restoreInstance(request: request, options: .init())
  }

  public func restoreInstance(
    request: RestoreInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func restoreInstancePollingUntilDone(request: RestoreInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.restoreInstancePollingUntilDone(request: request, options: .init())
  }

  public func restoreInstancePollingUntilDone(
    request: RestoreInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func revertInstance(request: RevertInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.revertInstance(request: request, options: .init())
  }

  public func revertInstance(
    request: RevertInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func revertInstancePollingUntilDone(request: RevertInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.revertInstancePollingUntilDone(request: request, options: .init())
  }

  public func revertInstancePollingUntilDone(
    request: RevertInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteInstancePollingUntilDone(request: request, options: .init())
  }

  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstancePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteInstanceRequest().with {
      $0.name = name
    }
    return try await self.deleteInstancePollingUntilDone(request: request)
  }

  public func listSnapshots(request: ListSnapshotsRequest) async throws
    -> GoogleCloudFilestoreV1.ListSnapshotsResponse
  {
    try await self.listSnapshots(request: request, options: .init())
  }

  public func listSnapshots(
    request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listSnapshotsByItems(
    request: ListSnapshotsRequest
  ) -> any AsyncSequence<Snapshot, Swift.Error> & Sendable {
    self.listSnapshotsByItems(request: request, options: .init())
  }

  /// Lists all snapshots in a project for either a specified location
  /// or for all locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListSnapshots")
  public func listSnapshotsByItems(
    request: ListSnapshotsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Snapshot, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listSnapshots(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSnapshotsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Snapshot, Swift.Error> & Sendable {
    let request = ListSnapshotsRequest().with {
      $0.parent = parent
    }
    return self.listSnapshotsByItems(request: request)
  }

  public func getSnapshot(request: GetSnapshotRequest) async throws
    -> GoogleCloudFilestoreV1.Snapshot
  {
    try await self.getSnapshot(request: request, options: .init())
  }

  public func getSnapshot(
    request: GetSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Snapshot {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSnapshot(
    name: Swift.String,
  ) async throws -> GoogleCloudFilestoreV1.Snapshot {
    let request = GetSnapshotRequest().with {
      $0.name = name
    }
    return try await self.getSnapshot(request: request)
  }

  public func createSnapshot(request: CreateSnapshotRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createSnapshot(request: request, options: .init())
  }

  public func createSnapshot(
    request: CreateSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createSnapshotPollingUntilDone(request: CreateSnapshotRequest) async throws
    -> any GoogleGax.PollableOperation<Snapshot>
  {
    try await self.createSnapshotPollingUntilDone(request: request, options: .init())
  }

  public func createSnapshotPollingUntilDone(
    request: CreateSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Snapshot>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createSnapshotPollingUntilDone(
    parent: Swift.String,
    snapshot: Snapshot?,
    snapshotId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let request = CreateSnapshotRequest().with {
      $0.parent = parent
      $0.snapshot = snapshot
      $0.snapshotId = snapshotId
    }
    return try await self.createSnapshotPollingUntilDone(request: request)
  }

  public func deleteSnapshot(request: DeleteSnapshotRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteSnapshot(request: request, options: .init())
  }

  public func deleteSnapshot(
    request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteSnapshotPollingUntilDone(request: DeleteSnapshotRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteSnapshotPollingUntilDone(request: request, options: .init())
  }

  public func deleteSnapshotPollingUntilDone(
    request: DeleteSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteSnapshotPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteSnapshotRequest().with {
      $0.name = name
    }
    return try await self.deleteSnapshotPollingUntilDone(request: request)
  }

  public func updateSnapshot(request: UpdateSnapshotRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateSnapshot(request: request, options: .init())
  }

  public func updateSnapshot(
    request: UpdateSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateSnapshotPollingUntilDone(request: UpdateSnapshotRequest) async throws
    -> any GoogleGax.PollableOperation<Snapshot>
  {
    try await self.updateSnapshotPollingUntilDone(request: request, options: .init())
  }

  public func updateSnapshotPollingUntilDone(
    request: UpdateSnapshotRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Snapshot>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateSnapshotPollingUntilDone(
    snapshot: Snapshot?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Snapshot> {
    let request = UpdateSnapshotRequest().with {
      $0.snapshot = snapshot
      $0.updateMask = updateMask
    }
    return try await self.updateSnapshotPollingUntilDone(request: request)
  }

  public func listBackups(request: ListBackupsRequest) async throws
    -> GoogleCloudFilestoreV1.ListBackupsResponse
  {
    try await self.listBackups(request: request, options: .init())
  }

  public func listBackups(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listBackupsByItems(
    request: ListBackupsRequest
  ) -> any AsyncSequence<Backup, Swift.Error> & Sendable {
    self.listBackupsByItems(request: request, options: .init())
  }

  /// Lists all backups in a project for either a specified location or for all
  /// locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListBackups")
  public func listBackupsByItems(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Backup, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse in
      var request = request
      request.pageToken = token
      return try await self.listBackups(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackupsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Backup, Swift.Error> & Sendable {
    let request = ListBackupsRequest().with {
      $0.parent = parent
    }
    return self.listBackupsByItems(request: request)
  }

  public func getBackup(request: GetBackupRequest) async throws -> GoogleCloudFilestoreV1.Backup {
    try await self.getBackup(request: request, options: .init())
  }

  public func getBackup(
    request: GetBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Backup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBackup(
    name: Swift.String,
  ) async throws -> GoogleCloudFilestoreV1.Backup {
    let request = GetBackupRequest().with {
      $0.name = name
    }
    return try await self.getBackup(request: request)
  }

  public func createBackup(request: CreateBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createBackup(request: request, options: .init())
  }

  public func createBackup(
    request: CreateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createBackupPollingUntilDone(request: CreateBackupRequest) async throws
    -> any GoogleGax.PollableOperation<Backup>
  {
    try await self.createBackupPollingUntilDone(request: request, options: .init())
  }

  public func createBackupPollingUntilDone(
    request: CreateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createBackupPollingUntilDone(
    parent: Swift.String,
    backup: Backup?,
    backupId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let request = CreateBackupRequest().with {
      $0.parent = parent
      $0.backup = backup
      $0.backupId = backupId
    }
    return try await self.createBackupPollingUntilDone(request: request)
  }

  public func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteBackup(request: request, options: .init())
  }

  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteBackupPollingUntilDone(request: DeleteBackupRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteBackupPollingUntilDone(request: request, options: .init())
  }

  public func deleteBackupPollingUntilDone(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteBackupPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteBackupRequest().with {
      $0.name = name
    }
    return try await self.deleteBackupPollingUntilDone(request: request)
  }

  public func updateBackup(request: UpdateBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.updateBackup(request: request, options: .init())
  }

  public func updateBackup(
    request: UpdateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateBackupPollingUntilDone(request: UpdateBackupRequest) async throws
    -> any GoogleGax.PollableOperation<Backup>
  {
    try await self.updateBackupPollingUntilDone(request: request, options: .init())
  }

  public func updateBackupPollingUntilDone(
    request: UpdateBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateBackupPollingUntilDone(
    backup: Backup?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let request = UpdateBackupRequest().with {
      $0.backup = backup
      $0.updateMask = updateMask
    }
    return try await self.updateBackupPollingUntilDone(request: request)
  }

  public func promoteReplica(request: PromoteReplicaRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.promoteReplica(request: request, options: .init())
  }

  public func promoteReplica(
    request: PromoteReplicaRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func promoteReplicaPollingUntilDone(request: PromoteReplicaRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.promoteReplicaPollingUntilDone(request: request, options: .init())
  }

  public func promoteReplicaPollingUntilDone(
    request: PromoteReplicaRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
