// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudCommon
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Configures and manages Filestore resources.
///
/// Filestore Manager v1.
///
/// The `file.googleapis.com` service implements the Filestore API and
/// defines the following resource model for managing instances:
/// * The service works with a collection of cloud projects, named: `/projects/*`
/// * Each project has a collection of available locations, named: `/locations/*`
/// * Each location has a collection of instances and backups, named:
/// `/instances/*` and `/backups/*` respectively.
/// * As such, Filestore instances are resources of the form:
///   `/projects/{project_number}/locations/{location_id}/instances/{instance_id}`
///   and backups are resources of the form:
///   `/projects/{project_number}/locations/{location_id}/backup/{backup_id}`
///
/// Note that location_id must be a Google Cloud `zone` for instances, but
/// a Google Cloud `region` for backups; for example:
/// * `projects/12345/locations/us-central1-c/instances/my-filestore`
/// * `projects/12345/locations/us-central1/backups/my-backup`
///
/// @Snippet(path: "CloudFilestoreManagerQuickstart")
public class CloudFilestoreManagerClient: Clients.CloudFilestoreManagerProtocol {
  let inner: any Clients.CloudFilestoreManagerStub

  /// Creates a new `CloudFilestoreManagerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudFilestoreManagerStub = try Clients.CloudFilestoreManagerTransport(
      options)
    inner = Clients.CloudFilestoreManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudFilestoreManagerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists all instances in a project for either a specified location
  /// or for all locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Lists all instances in a project for either a specified location
  /// or for all locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListInstances")
  public func listInstances(
    byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details of a specific instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Creates an instance.
  /// When creating from a backup, the capacity of the new instance needs to be
  /// equal to or larger than the capacity of the backup (and also equal to or
  /// larger than the minimum capacity of the tier).
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateInstance")
  public func createInstance(
    request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInstance(request: request, options: options)
  }

  /// Creates an instance.
  /// When creating from a backup, the capacity of the new instance needs to be
  /// equal to or larger than the capacity of the backup (and also equal to or
  /// larger than the minimum capacity of the tier).
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateInstance")
  public func createInstance(
    withPolling: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the settings of a specific instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateInstance")
  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateInstance(request: request, options: options)
  }

  /// Updates the settings of a specific instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateInstance")
  public func updateInstance(
    withPolling: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Restores an existing instance's file share from a backup.
  ///
  /// The capacity of the instance needs to be equal to or larger than the
  /// capacity of the backup (and also equal to or larger than the minimum
  /// capacity of the tier).
  ///
  /// @Snippet(path: "CloudFilestoreManager_RestoreInstance")
  public func restoreInstance(
    request: RestoreInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.restoreInstance(request: request, options: options)
  }

  /// Restores an existing instance's file share from a backup.
  ///
  /// The capacity of the instance needs to be equal to or larger than the
  /// capacity of the backup (and also equal to or larger than the minimum
  /// capacity of the tier).
  ///
  /// @Snippet(path: "CloudFilestoreManager_RestoreInstance")
  public func restoreInstance(
    withPolling: RestoreInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.restoreInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Revert an existing instance's file system to a specified snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_RevertInstance")
  public func revertInstance(
    request: RevertInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.revertInstance(request: request, options: options)
  }

  /// Revert an existing instance's file system to a specified snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_RevertInstance")
  public func revertInstance(
    withPolling: RevertInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.revertInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes an instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Deletes an instance.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteInstance")
  public func deleteInstance(
    withPolling: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteInstance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists all snapshots in a project for either a specified location
  /// or for all locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListSnapshots")
  public func listSnapshots(
    request: ListSnapshotsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse {
    try await self.inner.listSnapshots(request: request, options: options)
  }

  /// Lists all snapshots in a project for either a specified location
  /// or for all locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListSnapshots")
  public func listSnapshots(
    byItem: ListSnapshotsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Snapshot, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSnapshots(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details of a specific snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetSnapshot")
  public func getSnapshot(
    request: GetSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Snapshot {
    try await self.inner.getSnapshot(request: request, options: options)
  }

  /// Creates a snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateSnapshot")
  public func createSnapshot(
    request: CreateSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createSnapshot(request: request, options: options)
  }

  /// Creates a snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateSnapshot")
  public func createSnapshot(
    withPolling: CreateSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Snapshot>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Snapshot(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createSnapshot(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Snapshot>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteSnapshot")
  public func deleteSnapshot(
    request: DeleteSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteSnapshot(request: request, options: options)
  }

  /// Deletes a snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteSnapshot")
  public func deleteSnapshot(
    withPolling: DeleteSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteSnapshot(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the settings of a specific snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateSnapshot")
  public func updateSnapshot(
    request: UpdateSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateSnapshot(request: request, options: options)
  }

  /// Updates the settings of a specific snapshot.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateSnapshot")
  public func updateSnapshot(
    withPolling: UpdateSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Snapshot>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Snapshot(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateSnapshot(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Snapshot>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists all backups in a project for either a specified location or for all
  /// locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListBackups")
  public func listBackups(
    request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse {
    try await self.inner.listBackups(request: request, options: options)
  }

  /// Lists all backups in a project for either a specified location or for all
  /// locations.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListBackups")
  public func listBackups(
    byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listBackups(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details of a specific backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetBackup")
  public func getBackup(
    request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Backup {
    try await self.inner.getBackup(request: request, options: options)
  }

  /// Creates a backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateBackup")
  public func createBackup(
    request: CreateBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createBackup(request: request, options: options)
  }

  /// Creates a backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_CreateBackup")
  public func createBackup(
    withPolling: CreateBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Backup(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteBackup")
  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteBackup(request: request, options: options)
  }

  /// Deletes a backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteBackup")
  public func deleteBackup(
    withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the settings of a specific backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateBackup")
  public func updateBackup(
    request: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateBackup(request: request, options: options)
  }

  /// Updates the settings of a specific backup.
  ///
  /// @Snippet(path: "CloudFilestoreManager_UpdateBackup")
  public func updateBackup(
    withPolling: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Backup(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Promote the standby instance (replica).
  ///
  /// @Snippet(path: "CloudFilestoreManager_PromoteReplica")
  public func promoteReplica(
    request: PromoteReplicaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.promoteReplica(request: request, options: options)
  }

  /// Promote the standby instance (replica).
  ///
  /// @Snippet(path: "CloudFilestoreManager_PromoteReplica")
  public func promoteReplica(
    withPolling: PromoteReplicaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Instance(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.promoteReplica(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "CloudFilestoreManager_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "CloudFilestoreManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "CloudFilestoreManager_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "CloudFilestoreManager_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudFilestoreManagerClient`.
  ///
  /// To mock `CloudFilestoreManagerClient` change your functions to receive
  /// `some CloudFilestoreManagerProtocol` or `any CloudFilestoreManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudFilestoreManagerProtocol {
    /// See `CloudFilestoreManagerClient.listInstances`.
    func listInstances(request: ListInstancesRequest) async throws
      -> GoogleCloudFilestoreV1.ListInstancesResponse

    /// See `CloudFilestoreManagerClient.listInstances`.
    func listInstances(
      byItem: ListInstancesRequest
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `CloudFilestoreManagerClient.listInstances`.
    func listInstances(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `CloudFilestoreManagerClient.getInstance`.
    func getInstance(request: GetInstanceRequest) async throws -> GoogleCloudFilestoreV1.Instance

    /// See `CloudFilestoreManagerClient.getInstance`.
    func getInstance(
      name: Swift.String,
    ) async throws -> GoogleCloudFilestoreV1.Instance

    /// See `CloudFilestoreManagerClient.createInstance`.
    func createInstance(request: CreateInstanceRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createInstance`.
    func createInstance(withPolling: CreateInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.createInstance`.
    func createInstance(
      parent: Swift.String,
      instance: Instance?,
      instanceId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.updateInstance`.
    func updateInstance(request: UpdateInstanceRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateInstance`.
    func updateInstance(withPolling: UpdateInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.updateInstance`.
    func updateInstance(
      instance: Instance?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.restoreInstance`.
    func restoreInstance(request: RestoreInstanceRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.restoreInstance`.
    func restoreInstance(withPolling: RestoreInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.revertInstance`.
    func revertInstance(request: RevertInstanceRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.revertInstance`.
    func revertInstance(withPolling: RevertInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.deleteInstance`.
    func deleteInstance(request: DeleteInstanceRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteInstance`.
    func deleteInstance(withPolling: DeleteInstanceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.deleteInstance`.
    func deleteInstance(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.listSnapshots`.
    func listSnapshots(request: ListSnapshotsRequest) async throws
      -> GoogleCloudFilestoreV1.ListSnapshotsResponse

    /// See `CloudFilestoreManagerClient.listSnapshots`.
    func listSnapshots(
      byItem: ListSnapshotsRequest
    ) throws -> any AsyncSequence<Snapshot, Swift.Error>

    /// See `CloudFilestoreManagerClient.listSnapshots`.
    func listSnapshots(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Snapshot, Swift.Error>

    /// See `CloudFilestoreManagerClient.getSnapshot`.
    func getSnapshot(request: GetSnapshotRequest) async throws -> GoogleCloudFilestoreV1.Snapshot

    /// See `CloudFilestoreManagerClient.getSnapshot`.
    func getSnapshot(
      name: Swift.String,
    ) async throws -> GoogleCloudFilestoreV1.Snapshot

    /// See `CloudFilestoreManagerClient.createSnapshot`.
    func createSnapshot(request: CreateSnapshotRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createSnapshot`.
    func createSnapshot(withPolling: CreateSnapshotRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Snapshot>

    /// See `CloudFilestoreManagerClient.createSnapshot`.
    func createSnapshot(
      parent: Swift.String,
      snapshot: Snapshot?,
      snapshotId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot>

    /// See `CloudFilestoreManagerClient.deleteSnapshot`.
    func deleteSnapshot(request: DeleteSnapshotRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteSnapshot`.
    func deleteSnapshot(withPolling: DeleteSnapshotRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.deleteSnapshot`.
    func deleteSnapshot(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.updateSnapshot`.
    func updateSnapshot(request: UpdateSnapshotRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateSnapshot`.
    func updateSnapshot(withPolling: UpdateSnapshotRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Snapshot>

    /// See `CloudFilestoreManagerClient.updateSnapshot`.
    func updateSnapshot(
      snapshot: Snapshot?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot>

    /// See `CloudFilestoreManagerClient.listBackups`.
    func listBackups(request: ListBackupsRequest) async throws
      -> GoogleCloudFilestoreV1.ListBackupsResponse

    /// See `CloudFilestoreManagerClient.listBackups`.
    func listBackups(
      byItem: ListBackupsRequest
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `CloudFilestoreManagerClient.listBackups`.
    func listBackups(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `CloudFilestoreManagerClient.getBackup`.
    func getBackup(request: GetBackupRequest) async throws -> GoogleCloudFilestoreV1.Backup

    /// See `CloudFilestoreManagerClient.getBackup`.
    func getBackup(
      name: Swift.String,
    ) async throws -> GoogleCloudFilestoreV1.Backup

    /// See `CloudFilestoreManagerClient.createBackup`.
    func createBackup(request: CreateBackupRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createBackup`.
    func createBackup(withPolling: CreateBackupRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Backup>

    /// See `CloudFilestoreManagerClient.createBackup`.
    func createBackup(
      parent: Swift.String,
      backup: Backup?,
      backupId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Backup>

    /// See `CloudFilestoreManagerClient.deleteBackup`.
    func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteBackup`.
    func deleteBackup(withPolling: DeleteBackupRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.deleteBackup`.
    func deleteBackup(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.updateBackup`.
    func updateBackup(request: UpdateBackupRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateBackup`.
    func updateBackup(withPolling: UpdateBackupRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Backup>

    /// See `CloudFilestoreManagerClient.updateBackup`.
    func updateBackup(
      backup: Backup?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Backup>

    /// See `CloudFilestoreManagerClient.promoteReplica`.
    func promoteReplica(request: PromoteReplicaRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.promoteReplica`.
    func promoteReplica(withPolling: PromoteReplicaRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudFilestoreManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `CloudFilestoreManagerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `CloudFilestoreManagerClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `CloudFilestoreManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudFilestoreManagerClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudFilestoreManagerClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `CloudFilestoreManagerClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `CloudFilestoreManagerClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `CloudFilestoreManagerClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `CloudFilestoreManagerClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse

    /// See `CloudFilestoreManagerClient.listInstances`.
    func listInstances(
      byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Instance, Swift.Error>

    /// See `CloudFilestoreManagerClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Instance

    /// See `CloudFilestoreManagerClient.createInstance`.
    func createInstance(
      request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createInstance`.
    func createInstance(
      withPolling: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.updateInstance`.
    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateInstance`.
    func updateInstance(
      withPolling: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.restoreInstance`.
    func restoreInstance(
      request: RestoreInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.restoreInstance`.
    func restoreInstance(
      withPolling: RestoreInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.revertInstance`.
    func revertInstance(
      request: RevertInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.revertInstance`.
    func revertInstance(
      withPolling: RevertInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteInstance`.
    func deleteInstance(
      withPolling: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.listSnapshots`.
    func listSnapshots(
      request: ListSnapshotsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse

    /// See `CloudFilestoreManagerClient.listSnapshots`.
    func listSnapshots(
      byItem: ListSnapshotsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Snapshot, Swift.Error>

    /// See `CloudFilestoreManagerClient.getSnapshot`.
    func getSnapshot(
      request: GetSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Snapshot

    /// See `CloudFilestoreManagerClient.createSnapshot`.
    func createSnapshot(
      request: CreateSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createSnapshot`.
    func createSnapshot(
      withPolling: CreateSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot>

    /// See `CloudFilestoreManagerClient.deleteSnapshot`.
    func deleteSnapshot(
      request: DeleteSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteSnapshot`.
    func deleteSnapshot(
      withPolling: DeleteSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.updateSnapshot`.
    func updateSnapshot(
      request: UpdateSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateSnapshot`.
    func updateSnapshot(
      withPolling: UpdateSnapshotRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot>

    /// See `CloudFilestoreManagerClient.listBackups`.
    func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse

    /// See `CloudFilestoreManagerClient.listBackups`.
    func listBackups(
      byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `CloudFilestoreManagerClient.getBackup`.
    func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudFilestoreV1.Backup

    /// See `CloudFilestoreManagerClient.createBackup`.
    func createBackup(
      request: CreateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.createBackup`.
    func createBackup(
      withPolling: CreateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Backup>

    /// See `CloudFilestoreManagerClient.deleteBackup`.
    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.deleteBackup`.
    func deleteBackup(
      withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `CloudFilestoreManagerClient.updateBackup`.
    func updateBackup(
      request: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.updateBackup`.
    func updateBackup(
      withPolling: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Backup>

    /// See `CloudFilestoreManagerClient.promoteReplica`.
    func promoteReplica(
      request: PromoteReplicaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudFilestoreManagerClient.promoteReplica`.
    func promoteReplica(
      withPolling: PromoteReplicaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Instance>

    /// See `CloudFilestoreManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudFilestoreManagerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `CloudFilestoreManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `CloudFilestoreManagerClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `CloudFilestoreManagerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudFilestoreManagerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `CloudFilestoreManagerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.CloudFilestoreManagerProtocol {
  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudFilestoreV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listInstances(
    byItem: ListInstancesRequest
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    try self.listInstances(byItem: byItem, options: .init())
  }

  public func listInstances(
    byItem: ListInstancesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListInstancesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInstances(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Instance, Swift.Error> {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return try self.listInstances(byItem: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudFilestoreV1.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Instance {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudFilestoreV1.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func createInstance(request: CreateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInstance(request: request, options: .init())
  }

  public func createInstance(
    request: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createInstance(withPolling: CreateInstanceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Instance>
  {
    try await self.createInstance(withPolling: withPolling, options: .init())
  }

  public func createInstance(
    withPolling: CreateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInstance(
    parent: Swift.String,
    instance: Instance?,
    instanceId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let request = CreateInstanceRequest().with {
      $0.parent = parent
      $0.instance = instance
      $0.instanceId = instanceId
    }
    return try await self.createInstance(withPolling: request)
  }

  public func updateInstance(request: UpdateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateInstance(request: request, options: .init())
  }

  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateInstance(withPolling: UpdateInstanceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Instance>
  {
    try await self.updateInstance(withPolling: withPolling, options: .init())
  }

  public func updateInstance(
    withPolling: UpdateInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateInstance(
    instance: Instance?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let request = UpdateInstanceRequest().with {
      $0.instance = instance
      $0.updateMask = updateMask
    }
    return try await self.updateInstance(withPolling: request)
  }

  public func restoreInstance(request: RestoreInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.restoreInstance(request: request, options: .init())
  }

  public func restoreInstance(
    request: RestoreInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func restoreInstance(withPolling: RestoreInstanceRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Instance>
  {
    try await self.restoreInstance(withPolling: withPolling, options: .init())
  }

  public func restoreInstance(
    withPolling: RestoreInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func revertInstance(request: RevertInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.revertInstance(request: request, options: .init())
  }

  public func revertInstance(
    request: RevertInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func revertInstance(withPolling: RevertInstanceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Instance>
  {
    try await self.revertInstance(withPolling: withPolling, options: .init())
  }

  public func revertInstance(
    withPolling: RevertInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteInstance(withPolling: DeleteInstanceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteInstance(withPolling: withPolling, options: .init())
  }

  public func deleteInstance(
    withPolling: DeleteInstanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstance(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteInstanceRequest().with {
      $0.name = name
    }
    return try await self.deleteInstance(withPolling: request)
  }

  public func listSnapshots(request: ListSnapshotsRequest) async throws
    -> GoogleCloudFilestoreV1.ListSnapshotsResponse
  {
    try await self.listSnapshots(request: request, options: .init())
  }

  public func listSnapshots(
    request: ListSnapshotsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSnapshots(
    byItem: ListSnapshotsRequest
  ) throws -> any AsyncSequence<Snapshot, Swift.Error> {
    try self.listSnapshots(byItem: byItem, options: .init())
  }

  public func listSnapshots(
    byItem: ListSnapshotsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Snapshot, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListSnapshotsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSnapshots(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Snapshot, Swift.Error> {
    let request = ListSnapshotsRequest().with {
      $0.parent = parent
    }
    return try self.listSnapshots(byItem: request)
  }

  public func getSnapshot(request: GetSnapshotRequest) async throws
    -> GoogleCloudFilestoreV1.Snapshot
  {
    try await self.getSnapshot(request: request, options: .init())
  }

  public func getSnapshot(
    request: GetSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Snapshot {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSnapshot(
    name: Swift.String,
  ) async throws -> GoogleCloudFilestoreV1.Snapshot {
    let request = GetSnapshotRequest().with {
      $0.name = name
    }
    return try await self.getSnapshot(request: request)
  }

  public func createSnapshot(request: CreateSnapshotRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createSnapshot(request: request, options: .init())
  }

  public func createSnapshot(
    request: CreateSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSnapshot(withPolling: CreateSnapshotRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Snapshot>
  {
    try await self.createSnapshot(withPolling: withPolling, options: .init())
  }

  public func createSnapshot(
    withPolling: CreateSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Snapshot>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createSnapshot(
    parent: Swift.String,
    snapshot: Snapshot?,
    snapshotId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot> {
    let request = CreateSnapshotRequest().with {
      $0.parent = parent
      $0.snapshot = snapshot
      $0.snapshotId = snapshotId
    }
    return try await self.createSnapshot(withPolling: request)
  }

  public func deleteSnapshot(request: DeleteSnapshotRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteSnapshot(request: request, options: .init())
  }

  public func deleteSnapshot(
    request: DeleteSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSnapshot(withPolling: DeleteSnapshotRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteSnapshot(withPolling: withPolling, options: .init())
  }

  public func deleteSnapshot(
    withPolling: DeleteSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteSnapshot(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteSnapshotRequest().with {
      $0.name = name
    }
    return try await self.deleteSnapshot(withPolling: request)
  }

  public func updateSnapshot(request: UpdateSnapshotRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateSnapshot(request: request, options: .init())
  }

  public func updateSnapshot(
    request: UpdateSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSnapshot(withPolling: UpdateSnapshotRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Snapshot>
  {
    try await self.updateSnapshot(withPolling: withPolling, options: .init())
  }

  public func updateSnapshot(
    withPolling: UpdateSnapshotRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Snapshot>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateSnapshot(
    snapshot: Snapshot?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Snapshot> {
    let request = UpdateSnapshotRequest().with {
      $0.snapshot = snapshot
      $0.updateMask = updateMask
    }
    return try await self.updateSnapshot(withPolling: request)
  }

  public func listBackups(request: ListBackupsRequest) async throws
    -> GoogleCloudFilestoreV1.ListBackupsResponse
  {
    try await self.listBackups(request: request, options: .init())
  }

  public func listBackups(
    request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listBackups(
    byItem: ListBackupsRequest
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    try self.listBackups(byItem: byItem, options: .init())
  }

  public func listBackups(
    byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudFilestoreV1.ListBackupsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackups(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let request = ListBackupsRequest().with {
      $0.parent = parent
    }
    return try self.listBackups(byItem: request)
  }

  public func getBackup(request: GetBackupRequest) async throws -> GoogleCloudFilestoreV1.Backup {
    try await self.getBackup(request: request, options: .init())
  }

  public func getBackup(
    request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudFilestoreV1.Backup {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getBackup(
    name: Swift.String,
  ) async throws -> GoogleCloudFilestoreV1.Backup {
    let request = GetBackupRequest().with {
      $0.name = name
    }
    return try await self.getBackup(request: request)
  }

  public func createBackup(request: CreateBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createBackup(request: request, options: .init())
  }

  public func createBackup(
    request: CreateBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createBackup(withPolling: CreateBackupRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Backup>
  {
    try await self.createBackup(withPolling: withPolling, options: .init())
  }

  public func createBackup(
    withPolling: CreateBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createBackup(
    parent: Swift.String,
    backup: Backup?,
    backupId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let request = CreateBackupRequest().with {
      $0.parent = parent
      $0.backup = backup
      $0.backupId = backupId
    }
    return try await self.createBackup(withPolling: request)
  }

  public func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteBackup(request: request, options: .init())
  }

  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteBackup(withPolling: DeleteBackupRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteBackup(withPolling: withPolling, options: .init())
  }

  public func deleteBackup(
    withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteBackup(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteBackupRequest().with {
      $0.name = name
    }
    return try await self.deleteBackup(withPolling: request)
  }

  public func updateBackup(request: UpdateBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.updateBackup(request: request, options: .init())
  }

  public func updateBackup(
    request: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateBackup(withPolling: UpdateBackupRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Backup>
  {
    try await self.updateBackup(withPolling: withPolling, options: .init())
  }

  public func updateBackup(
    withPolling: UpdateBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateBackup(
    backup: Backup?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let request = UpdateBackupRequest().with {
      $0.backup = backup
      $0.updateMask = updateMask
    }
    return try await self.updateBackup(withPolling: request)
  }

  public func promoteReplica(request: PromoteReplicaRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.promoteReplica(request: request, options: .init())
  }

  public func promoteReplica(
    request: PromoteReplicaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func promoteReplica(withPolling: PromoteReplicaRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Instance>
  {
    try await self.promoteReplica(withPolling: withPolling, options: .init())
  }

  public func promoteReplica(
    withPolling: PromoteReplicaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Instance>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
