// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// CreateInstanceRequest creates an instance.
public struct CreateInstanceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The instance's project and location, in the format
  /// `projects/{project_id}/locations/{location}`. In Filestore,
  /// locations map to Google Cloud zones, for example **us-west1-b**.
  public var parent: Swift.String

  /// Required. The name of the instance to create.
  /// The name must be unique for the specified project and location.
  public var instanceId: Swift.String

  /// Required. An [instance resource][google.cloud.filestore.v1.Instance]
  ///
  /// [google.cloud.filestore.v1.Instance]: <doc:Instance>
  public var instance: Instance?

  /// Initialize a new instance of `CreateInstanceRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    instanceId: Swift.String = Swift.String(),
    instance: Instance? = nil,
  ) {
    self.parent = parent
    self.instanceId = instanceId
    self.instance = instance
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.filestore.v1.CreateInstanceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
