// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// CreateBackupRequest creates a backup.
public struct CreateBackupRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The backup's project and location, in the format
  /// `projects/{project_number}/locations/{location}`. In Filestore,
  /// backup locations map to Google Cloud regions, for example **us-west1**.
  public var parent: Swift.String = Swift.String()

  /// Required. A [backup resource][google.cloud.filestore.v1.Backup]
  ///
  /// [google.cloud.filestore.v1.Backup]: <doc:Backup>
  public var backup: Backup? = nil

  /// Required. The ID to use for the backup.
  /// The ID must be unique within the specified project and location.
  ///
  /// This value must start with a lowercase letter followed by up to 62
  /// lowercase letters, numbers, or hyphens, and cannot end with a hyphen.
  /// Values that do not match this pattern will trigger an INVALID_ARGUMENT
  /// error.
  public var backupId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateBackupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateBackupRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.filestore.v1.CreateBackupRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
