// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// DeleteInstanceRequest deletes an instance.
public struct DeleteInstanceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The instance resource name, in the format
  /// `projects/{project_id}/locations/{location}/instances/{instance_id}`
  public var name: Swift.String

  /// If set to true, all snapshots of the instance will also be deleted.
  /// (Otherwise, the request will only work if the instance has no snapshots.)
  public var force: Swift.Bool

  /// Initialize a new instance of `DeleteInstanceRequest`.
  public init(
    name: Swift.String = Swift.String(),
    force: Swift.Bool = Swift.Bool(),
  ) {
    self.name = name
    self.force = force
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.filestore.v1.DeleteInstanceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
