// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// File share configuration for the instance.
public struct FileShareConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the file share. Must use 1-16 characters for the
  /// basic service tier and 1-63 characters for all other service tiers.
  /// Must use lowercase letters, numbers, or underscores `[a-z0-9_]`. Must
  /// start with a letter. Immutable.
  public var name: Swift.String = Swift.String()

  /// File share capacity in gigabytes (GB).
  /// Filestore defines 1 GB as 1024^3 bytes.
  public var capacityGb: Swift.Int64 = Swift.Int64()

  /// Nfs Export Options.
  /// There is a limit of 10 export options per file share.
  public var nfsExportOptions: [NfsExportOptions] = []

  /// The source that this file share has been restored from. Empty if the file
  /// share is created from scratch.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FileShareConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FileShareConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let capacityGb = CodingKeys(stringValue: "capacityGb")
    static let sourceBackup = CodingKeys(stringValue: "sourceBackup")
    static let nfsExportOptions = CodingKeys(stringValue: "nfsExportOptions")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "capacityGb",
      "sourceBackup",
      "nfsExportOptions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .capacityGb) {
      self.capacityGb = value
    }
    if let value = try container.decodeIfPresent([NfsExportOptions].self, forKey: .nfsExportOptions)
    {
      self.nfsExportOptions = value
    }

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let sourceBackup = try container.decodeIfPresent(Swift.String.self, forKey: .sourceBackup) {
      try sourceCheckAndSet(.sourceBackup(sourceBackup))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.capacityGb, forKey: .capacityGb)
    try container.encode(self.nfsExportOptions, forKey: .nfsExportOptions)

    if let choice = self.source {
      switch choice {
      case .sourceBackup(let value):
        try container.encode(value, forKey: .sourceBackup)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The source that this file share has been restored from. Empty if the file
  /// share is created from scratch.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// The resource name of the backup, in the format
    /// `projects/{project_number}/locations/{location_id}/backups/{backup_id}`,
    /// that this file share has been restored from.
    case sourceBackup(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.filestore.v1.FileShareConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
