// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Filestore instance.
public struct Instance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the instance, in the format
  /// `projects/{project}/locations/{location}/instances/{instance}`.
  public var name: Swift.String = Swift.String()

  /// The description of the instance (2048 characters or less).
  public var description: Swift.String = Swift.String()

  /// Output only. The instance state.
  public var state: Instance.State = Instance.State()

  /// Output only. Additional information about the instance state, if available.
  public var statusMessage: Swift.String = Swift.String()

  /// Output only. The time when the instance was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// The service tier of the instance.
  public var tier: Instance.Tier = Instance.Tier()

  /// Resource labels to represent user provided metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// File system shares on the instance.
  /// For this version, only a single file share is supported.
  public var fileShares: [FileShareConfig] = []

  /// VPC networks to which the instance is connected.
  /// For this version, only a single network is supported.
  public var networks: [NetworkConfig] = []

  /// Server-specified ETag for the instance resource to prevent simultaneous
  /// updates from overwriting each other.
  public var etag: Swift.String = Swift.String()

  /// Output only. Reserved for future use.
  public var satisfiesPzs: GoogleCloudWkt.BoolValue? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// KMS key name used for data encryption.
  public var kmsKeyName: Swift.String = Swift.String()

  /// Output only. Field indicates all the reasons the instance is in "SUSPENDED"
  /// state.
  public var suspensionReasons: [Instance.SuspensionReason] = []

  /// Optional. Replication configuration.
  public var replication: Replication? = nil

  /// Optional. Input only. Immutable. Tag key-value pairs bound to this
  /// resource. Each key must be a namespaced name and each value a short name.
  /// Example:
  /// "123456789012/environment" : "production",
  /// "123456789013/costCenter" : "marketing"
  /// See the documentation for more information:
  /// - Namespaced name:
  /// https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#retrieving_tag_key
  /// - Short name:
  /// https://cloud.google.com/resource-manager/docs/tags/tags-creating-and-managing#retrieving_tag_value
  public var tags: [Swift.String: Swift.String] = [:]

  /// Immutable. The protocol indicates the access protocol for all shares in the
  /// instance. This field is immutable and it cannot be changed after the
  /// instance has been created. Default value: `NFS_V3`.
  public var `protocol`: Instance.FileProtocol = Instance.FileProtocol()

  /// Output only. Indicates whether this instance supports configuring its
  /// performance. If true, the user can configure the instance's performance by
  /// using the 'performance_config' field.
  public var customPerformanceSupported: Swift.Bool = Swift.Bool()

  /// Optional. Used to configure performance.
  public var performanceConfig: Instance.PerformanceConfig? = nil

  /// Output only. Used for getting performance limits.
  public var performanceLimits: Instance.PerformanceLimits? = nil

  /// Optional. Indicates whether the instance is protected against deletion.
  public var deletionProtectionEnabled: Swift.Bool = Swift.Bool()

  /// Optional. The reason for enabling deletion protection.
  public var deletionProtectionReason: Swift.String = Swift.String()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case name = "name"
    case description = "description"
    case state = "state"
    case statusMessage = "statusMessage"
    case createTime = "createTime"
    case tier = "tier"
    case labels = "labels"
    case fileShares = "fileShares"
    case networks = "networks"
    case etag = "etag"
    case satisfiesPzs = "satisfiesPzs"
    case satisfiesPzi = "satisfiesPzi"
    case kmsKeyName = "kmsKeyName"
    case suspensionReasons = "suspensionReasons"
    case replication = "replication"
    case tags = "tags"
    case `protocol` = "protocol"
    case customPerformanceSupported = "customPerformanceSupported"
    case performanceConfig = "performanceConfig"
    case performanceLimits = "performanceLimits"
    case deletionProtectionEnabled = "deletionProtectionEnabled"
    case deletionProtectionReason = "deletionProtectionReason"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.state = try container.decode(Instance.State.self, forKey: .state)
    self.statusMessage = try container.decode(Swift.String.self, forKey: .statusMessage)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.tier = try container.decode(Instance.Tier.self, forKey: .tier)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.fileShares = try container.decode([FileShareConfig].self, forKey: .fileShares)
    self.networks = try container.decode([NetworkConfig].self, forKey: .networks)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)
    self.satisfiesPzs = try container.decodeIfPresent(
      GoogleCloudWkt.BoolValue.self, forKey: .satisfiesPzs)
    self.satisfiesPzi = try container.decode(Swift.Bool.self, forKey: .satisfiesPzi)
    self.kmsKeyName = try container.decode(Swift.String.self, forKey: .kmsKeyName)
    self.suspensionReasons = try container.decode(
      [Instance.SuspensionReason].self, forKey: .suspensionReasons)
    self.replication = try container.decodeIfPresent(Replication.self, forKey: .replication)
    self.tags = try container.decode([Swift.String: Swift.String].self, forKey: .tags)
    self.`protocol` = try container.decode(Instance.FileProtocol.self, forKey: .`protocol`)
    self.customPerformanceSupported = try container.decode(
      Swift.Bool.self, forKey: .customPerformanceSupported)
    self.performanceConfig = try container.decodeIfPresent(
      Instance.PerformanceConfig.self, forKey: .performanceConfig)
    self.performanceLimits = try container.decodeIfPresent(
      Instance.PerformanceLimits.self, forKey: .performanceLimits)
    self.deletionProtectionEnabled = try container.decode(
      Swift.Bool.self, forKey: .deletionProtectionEnabled)
    self.deletionProtectionReason = try container.decode(
      Swift.String.self, forKey: .deletionProtectionReason)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.statusMessage, forKey: .statusMessage)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.tier, forKey: .tier)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.fileShares, forKey: .fileShares)
    try container.encode(self.networks, forKey: .networks)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.satisfiesPzi, forKey: .satisfiesPzi)
    try container.encode(self.kmsKeyName, forKey: .kmsKeyName)
    try container.encode(self.suspensionReasons, forKey: .suspensionReasons)
    try container.encode(self.replication, forKey: .replication)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.customPerformanceSupported, forKey: .customPerformanceSupported)
    try container.encode(self.performanceConfig, forKey: .performanceConfig)
    try container.encode(self.performanceLimits, forKey: .performanceLimits)
    try container.encode(self.deletionProtectionEnabled, forKey: .deletionProtectionEnabled)
    try container.encode(self.deletionProtectionReason, forKey: .deletionProtectionReason)
  }

  /// IOPS per TB.
  /// Filestore defines TB as 1024^4 bytes (TiB).
  public struct IOPSPerTB: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Maximum IOPS per TiB.
    public var maxIopsPerTb: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `IOPSPerTB`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IOPSPerTB().with { $0.maxIopsPerTb = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.filestore.v1.Instance.IOPSPerTB"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Fixed IOPS (input/output operations per second) parameters.
  public struct FixedIOPS: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Maximum IOPS.
    public var maxIops: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `FixedIOPS`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FixedIOPS().with { $0.maxIops = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.filestore.v1.Instance.FixedIOPS"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Used for setting the performance configuration.
  /// If the user doesn't specify PerformanceConfig, automatically provision
  /// the default performance settings as described in
  /// https://cloud.google.com/filestore/docs/performance. Larger instances will
  /// be linearly set to more IOPS. If the instance's capacity is increased or
  /// decreased, its performance will be automatically adjusted upwards or
  /// downwards accordingly (respectively).
  public struct PerformanceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var mode: OneOf_Mode? = nil

    /// Initialize a new instance of `PerformanceConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PerformanceConfig().with { $0.iopsPerTb = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case iopsPerTb = "iopsPerTb"
      case fixedIops = "fixedIops"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var mode: OneOf_Mode? = nil
      let modeCheckAndSet = {
        if mode != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'mode'"))
        }
        mode = $0
      }
      if let iopsPerTb = try container.decodeIfPresent(Instance.IOPSPerTB?.self, forKey: .iopsPerTb)
      {
        try modeCheckAndSet(.iopsPerTb(iopsPerTb))
      }
      if let fixedIops = try container.decodeIfPresent(Instance.FixedIOPS?.self, forKey: .fixedIops)
      {
        try modeCheckAndSet(.fixedIops(fixedIops))
      }
      self.mode = mode
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.mode {
        switch choice {
        case .iopsPerTb(let value):
          try container.encode(value, forKey: .iopsPerTb)
        case .fixedIops(let value):
          try container.encode(value, forKey: .fixedIops)
        }
      }
    }

    public enum OneOf_Mode: Codable, Equatable, Sendable {
      /// Provision IOPS dynamically based on the capacity of the instance.
      /// Provisioned IOPS will be calculated by multiplying the capacity of the
      /// instance in TiB by the `iops_per_tb` value. For example, for a 2 TiB
      /// instance with an `iops_per_tb` value of 17000 the provisioned IOPS will
      /// be 34000.
      ///
      /// If the calculated value is outside the supported range for the
      /// instance's capacity during instance creation, instance creation will
      /// fail with an `InvalidArgument` error. Similarly, if an instance
      /// capacity update would result in a value outside the supported range,
      /// the update will fail with an `InvalidArgument` error.
      indirect case iopsPerTb(Instance.IOPSPerTB?)
      /// Choose a fixed provisioned IOPS value for the instance, which will
      /// remain constant regardless of instance capacity. Value must be a
      /// multiple of 1000.
      ///
      /// If the chosen value is outside the supported range for the instance's
      /// capacity during instance creation, instance creation will fail with an
      /// `InvalidArgument` error. Similarly, if an instance capacity update
      /// would result in a value outside the supported range, the update will
      /// fail with an `InvalidArgument` error.
      indirect case fixedIops(Instance.FixedIOPS?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.filestore.v1.Instance.PerformanceConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The enforced performance limits, calculated from the instance's performance
  /// configuration.
  public struct PerformanceLimits: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The max IOPS.
    public var maxIops: Swift.Int64 = Swift.Int64()

    /// Output only. The max read IOPS.
    public var maxReadIops: Swift.Int64 = Swift.Int64()

    /// Output only. The max write IOPS.
    public var maxWriteIops: Swift.Int64 = Swift.Int64()

    /// Output only. The max read throughput in bytes per second.
    public var maxReadThroughputBps: Swift.Int64 = Swift.Int64()

    /// Output only. The max write throughput in bytes per second.
    public var maxWriteThroughputBps: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `PerformanceLimits`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PerformanceLimits().with { $0.maxIops = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.filestore.v1.Instance.PerformanceLimits"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The instance state.
  public enum State: Codable, Equatable, Sendable {
    case unspecified
    case creating
    case ready
    case repairing
    case deleting
    case error
    case restoring
    case suspended
    case suspending
    case resuming
    case reverting
    case promoting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .repairing: return 3
      case .deleting: return 4
      case .error: return 6
      case .restoring: return 7
      case .suspended: return 8
      case .suspending: return 9
      case .resuming: return 10
      case .reverting: return 12
      case .promoting: return 13
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .repairing: return "REPAIRING"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .restoring: return "RESTORING"
      case .suspended: return "SUSPENDED"
      case .suspending: return "SUSPENDING"
      case .resuming: return "RESUMING"
      case .reverting: return "REVERTING"
      case .promoting: return "PROMOTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "REPAIRING": self = .repairing
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "RESTORING": self = .restoring
      case "SUSPENDED": self = .suspended
      case "SUSPENDING": self = .suspending
      case "RESUMING": self = .resuming
      case "REVERTING": self = .reverting
      case "PROMOTING": self = .promoting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .repairing
      case 4: self = .deleting
      case 6: self = .error
      case 7: self = .restoring
      case 8: self = .suspended
      case 9: self = .suspending
      case 10: self = .resuming
      case 12: self = .reverting
      case 13: self = .promoting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .repairing: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .error: return try container.encode(6)
      case .restoring: return try container.encode(7)
      case .suspended: return try container.encode(8)
      case .suspending: return try container.encode(9)
      case .resuming: return try container.encode(10)
      case .reverting: return try container.encode(12)
      case .promoting: return try container.encode(13)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Available service tiers.
  public enum Tier: Codable, Equatable, Sendable {
    case unspecified
    case standard
    case premium
    case basicHdd
    case basicSsd
    case highScaleSsd
    case enterprise
    case zonal
    case regional
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .premium: return 2
      case .basicHdd: return 3
      case .basicSsd: return 4
      case .highScaleSsd: return 5
      case .enterprise: return 6
      case .zonal: return 7
      case .regional: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "TIER_UNSPECIFIED"
      case .standard: return "STANDARD"
      case .premium: return "PREMIUM"
      case .basicHdd: return "BASIC_HDD"
      case .basicSsd: return "BASIC_SSD"
      case .highScaleSsd: return "HIGH_SCALE_SSD"
      case .enterprise: return "ENTERPRISE"
      case .zonal: return "ZONAL"
      case .regional: return "REGIONAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "TIER_UNSPECIFIED": self = .unspecified
      case "STANDARD": self = .standard
      case "PREMIUM": self = .premium
      case "BASIC_HDD": self = .basicHdd
      case "BASIC_SSD": self = .basicSsd
      case "HIGH_SCALE_SSD": self = .highScaleSsd
      case "ENTERPRISE": self = .enterprise
      case "ZONAL": self = .zonal
      case "REGIONAL": self = .regional
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .premium
      case 3: self = .basicHdd
      case 4: self = .basicSsd
      case 5: self = .highScaleSsd
      case 6: self = .enterprise
      case 7: self = .zonal
      case 8: self = .regional
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .standard: return try container.encode(1)
      case .premium: return try container.encode(2)
      case .basicHdd: return try container.encode(3)
      case .basicSsd: return try container.encode(4)
      case .highScaleSsd: return try container.encode(5)
      case .enterprise: return try container.encode(6)
      case .zonal: return try container.encode(7)
      case .regional: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// SuspensionReason contains the possible reasons for a suspension.
  public enum SuspensionReason: Codable, Equatable, Sendable {
    case unspecified
    case kmsKeyIssue
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .kmsKeyIssue: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "SUSPENSION_REASON_UNSPECIFIED"
      case .kmsKeyIssue: return "KMS_KEY_ISSUE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "SUSPENSION_REASON_UNSPECIFIED": self = .unspecified
      case "KMS_KEY_ISSUE": self = .kmsKeyIssue
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .kmsKeyIssue
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .kmsKeyIssue: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// File access protocol.
  public enum FileProtocol: Codable, Equatable, Sendable {
    case unspecified
    case nfsV3
    case nfsV41
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .nfsV3: return 1
      case .nfsV41: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "FILE_PROTOCOL_UNSPECIFIED"
      case .nfsV3: return "NFS_V3"
      case .nfsV41: return "NFS_V4_1"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "FILE_PROTOCOL_UNSPECIFIED": self = .unspecified
      case "NFS_V3": self = .nfsV3
      case "NFS_V4_1": self = .nfsV41
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .nfsV3
      case 2: self = .nfsV41
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .nfsV3: return try container.encode(1)
      case .nfsV41: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.filestore.v1.Instance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
