// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ListInstancesRequest lists instances.
public struct ListInstancesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location for which to retrieve instance
  /// information, in the format `projects/{project_id}/locations/{location}`. In
  /// Cloud Filestore, locations map to Google Cloud zones, for example
  /// **us-west1-b**. To retrieve instance information for all locations, use "-"
  /// for the
  /// `{location}` value.
  public var parent: Swift.String

  /// The maximum number of items to return.
  public var pageSize: Swift.Int32

  /// The next_page_token value to use if there are additional
  /// results to retrieve for this list request.
  public var pageToken: Swift.String

  /// Sort results. Supported values are "name", "name desc" or "" (unsorted).
  public var orderBy: Swift.String

  /// List filter.
  public var filter: Swift.String

  /// Initialize a new instance of `ListInstancesRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    pageSize: Swift.Int32 = Swift.Int32(),
    pageToken: Swift.String = Swift.String(),
    orderBy: Swift.String = Swift.String(),
    filter: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.pageSize = pageSize
    self.pageToken = pageToken
    self.orderBy = orderBy
    self.filter = filter
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.filestore.v1.ListInstancesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
