// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Network configuration for the instance.
public struct NetworkConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the Google Compute Engine
  /// [VPC network](https://cloud.google.com/vpc/docs/vpc) to which the
  /// instance is connected.
  public var network: Swift.String = Swift.String()

  /// Internet protocol versions for which the instance has IP addresses
  /// assigned. For this version, only MODE_IPV4 is supported.
  public var modes: [NetworkConfig.AddressMode] = []

  /// Optional, reserved_ip_range can have one of the following two types of
  /// values.
  ///
  /// * CIDR range value when using DIRECT_PEERING connect mode.
  /// * [Allocated IP address
  /// range](https://cloud.google.com/compute/docs/ip-addresses/reserve-static-internal-ip-address)
  /// when using PRIVATE_SERVICE_ACCESS connect mode.
  ///
  /// When the name of an allocated IP address range is specified, it must be one
  /// of the ranges associated with the private service access connection.
  /// When specified as a direct CIDR value, it must be a /29 CIDR block for
  /// Basic tier, a /24 CIDR block for High Scale tier, or a /26 CIDR block for
  /// Enterprise tier in one of the [internal IP address
  /// ranges](https://www.arin.net/reference/research/statistics/address_filters/)
  /// that identifies the range of IP addresses reserved for this instance. For
  /// example, 10.0.0.0/29, 192.168.0.0/24 or 192.168.0.0/26, respectively. The
  /// range you specify can't overlap with either existing subnets or assigned IP
  /// address ranges for other Filestore instances in the selected VPC
  /// network.
  public var reservedIpRange: Swift.String = Swift.String()

  /// Output only. IPv4 addresses in the format
  /// `{octet1}.{octet2}.{octet3}.{octet4}` or IPv6 addresses in the format
  /// `{block1}:{block2}:{block3}:{block4}:{block5}:{block6}:{block7}:{block8}`.
  public var ipAddresses: [Swift.String] = []

  /// The network connect mode of the Filestore instance.
  /// If not provided, the connect mode defaults to DIRECT_PEERING.
  public var connectMode: NetworkConfig.ConnectMode = NetworkConfig.ConnectMode()

  /// Initialize a new instance of `NetworkConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkConfig().with { $0.network = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Internet protocol versions supported by Filestore.
  public enum AddressMode: Codable, Equatable, Sendable {
    /// Internet protocol not set.
    case unspecified
    /// Use the IPv4 internet protocol.
    case modeIpv4
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .modeIpv4: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ADDRESS_MODE_UNSPECIFIED"
      case .modeIpv4: return "MODE_IPV4"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AddressMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ADDRESS_MODE_UNSPECIFIED": self = .unspecified
      case "MODE_IPV4": self = .modeIpv4
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AddressMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .modeIpv4
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .modeIpv4: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Available connection modes.
  public enum ConnectMode: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Connect via direct peering to the Filestore service.
    case directPeering
    /// Connect to your Filestore instance using Private Service
    /// Access. Private services access provides an IP address range for multiple
    /// Google Cloud services, including Filestore.
    case privateServiceAccess
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .directPeering: return 1
      case .privateServiceAccess: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CONNECT_MODE_UNSPECIFIED"
      case .directPeering: return "DIRECT_PEERING"
      case .privateServiceAccess: return "PRIVATE_SERVICE_ACCESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConnectMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CONNECT_MODE_UNSPECIFIED": self = .unspecified
      case "DIRECT_PEERING": self = .directPeering
      case "PRIVATE_SERVICE_ACCESS": self = .privateServiceAccess
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConnectMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .directPeering
      case 2: self = .privateServiceAccess
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .directPeering: return try container.encode(1)
      case .privateServiceAccess: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.filestore.v1.NetworkConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
