// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// PromoteReplicaRequest promotes a Filestore standby instance (replica).
public struct PromoteReplicaRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the instance, in the format
  /// `projects/{project_id}/locations/{location_id}/instances/{instance_id}`.
  public var name: Swift.String

  /// Optional. The resource name of the peer instance to promote, in the format
  /// `projects/{project_id}/locations/{location_id}/instances/{instance_id}`.
  /// The peer instance is required if the operation is called on an active
  /// instance.
  public var peerInstance: Swift.String

  /// Initialize a new instance of `PromoteReplicaRequest`.
  public init(
    name: Swift.String = Swift.String(),
    peerInstance: Swift.String = Swift.String(),
  ) {
    self.name = name
    self.peerInstance = peerInstance
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.filestore.v1.PromoteReplicaRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
