// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// RestoreInstanceRequest restores an existing instance's file share from a
/// backup.
public struct RestoreInstanceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the instance, in the format
  /// `projects/{project_number}/locations/{location_id}/instances/{instance_id}`.
  public var name: Swift.String

  /// Required. Name of the file share in the Filestore instance that the backup
  /// is being restored to.
  public var fileShare: Swift.String

  public var source: OneOf_Source?

  /// Initialize a new instance of `RestoreInstanceRequest`.
  public init(
    name: Swift.String = Swift.String(),
    fileShare: Swift.String = Swift.String(),
    source: OneOf_Source? = nil,
  ) {
    self.name = name
    self.fileShare = fileShare
    self.source = source
  }

  private enum CodingKeys: String, CodingKey {
    case name = "name"
    case fileShare = "fileShare"
    case sourceBackup = "sourceBackup"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.fileShare = try container.decode(Swift.String.self, forKey: .fileShare)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let sourceBackup = try container.decodeIfPresent(Swift.String.self, forKey: .sourceBackup) {
      try sourceCheckAndSet(.sourceBackup(sourceBackup))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.fileShare, forKey: .fileShare)

    if let choice = self.source {
      switch choice {
      case .sourceBackup(let value):
        try container.encode(value, forKey: .sourceBackup)
      }
    }
  }

  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// The resource name of the backup, in the format
    /// `projects/{project_number}/locations/{location_id}/backups/{backup_id}`.
    case sourceBackup(Swift.String)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.filestore.v1.RestoreInstanceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
