// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// RevertInstanceRequest reverts the given instance's file share to the
/// specified snapshot.
public struct RevertInstanceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the instance, in the format
  /// `projects/{project_id}/locations/{location_id}/instances/{instance_id}`.
  public var name: Swift.String

  /// Required. The snapshot resource ID, in the format 'my-snapshot', where the
  /// specified ID is the {snapshot_id} of the fully qualified name like
  /// `projects/{project_id}/locations/{location_id}/instances/{instance_id}/snapshots/{snapshot_id}`
  public var targetSnapshotId: Swift.String

  /// Initialize a new instance of `RevertInstanceRequest`.
  public init(
    name: Swift.String = Swift.String(),
    targetSnapshotId: Swift.String = Swift.String(),
  ) {
    self.name = name
    self.targetSnapshotId = targetSnapshotId
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.filestore.v1.RevertInstanceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
